name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          dotnet publish -a x64 -v d --no-self-contained

      - name: pack artifact
        run: |
          $releasePath = "./bin/Release/net8.0-windows/win-x64/publish"

          Copy-Item "$releasePath/MyPic_Anoㄙtator.exe" "./MyPic_Anontator.exe" -Recurse -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Its-MyPic-Anontator
          path: ./MyPic_Anontator.exe
