name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          dotnet publish

      - name: pack artifact
        run: |
          $releasePath = "./bin/Release/net8.0-windows/publish/win-x64"

          Copy-Item "$releasePath/MyPic_Annotator.exe" "./MyPic_Annotator.exe" -Recurse -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Its-MyPic-Annotator
          path: ./MyPic_Annotator.exe
